### PR TITLE
Update FileBrowser.cs

### PR DESCRIPTION
**Pull request by drew-512**
added ItemPassesFilter delegate -- nicer than extensions :)

### CODE REVIEW

**Comment by drew-512** [comment]
SimpleFileBrowser is awesome, thanks!

**Comment by yasirkula** [comment]
I get the idea behind this PR but this isn't something I've seen on any other file browser before. What kind of use-case prompted you to create this feature?

**Comment by yasirkula** [comment]
You can define [multiple extensions in a single filter](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/1238694a6b8726ab6e196a1c66ecf24923647504/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L64). Do you mean an extension `*.ext.zip` where `ext` part can be any 3-letter string? I honestly have never seen such flexible extensions used anywhere before.

**Comment by drew-512** [comment]
> You can define [multiple extensions in a single filter](https://github.com/yasirkula/UnitySimpleFileBrowser/blob/1238694a6b8726ab6e196a1c66ecf24923647504/Plugins/SimpleFileBrowser/Scripts/FileBrowser.cs#L64). Do you mean an extension `*.ext.zip` where `ext` part can be any 3-letter string? I honestly have never seen such flexible extensions used anywhere before.

No, I'm talking about making a filter that accepts, say, all files that that ends with ".dir.zip".  The current code only looks at the rightmost extension.

**Pull request closed without merging**
